import { Inter } from "next/font/google";
import { StateProvider } from './context/stateContext';
import Navlink from './components/Navlink'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "e-commerce project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        {/* Add other meta tags, link tags, or scripts here */}
      </head>
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <StateProvider>
            <Navlink />
            {children}
          </StateProvider>
          <footer className="mt-auto text-center p-4 text-xl">
            <small>
              Copyright © 2024 <span className=" bg-gradient-to-r from-cyan-500 to-green-500 text-transparent bg-clip-text">Fruitio</span>. All Rights Reserved.
            </small>
          </footer>
        </div>
      </body>
    </html>
  );
}
